
CREATE TABLE `question_list` (
  `QUESTION_ID` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `QUESTION_NAME` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `QUESTION_TYPE` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `QUESTION_ANSWER` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ANSWER_A` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ANSWER_B` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ANSWER_C` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ANSWER_D` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ANSWER_E` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ANSWER_F` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ANSWER_G` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `INACTIVE_TIME` datetime DEFAULT NULL,
  `ACTIVE_TIME` datetime DEFAULT NULL,
  `STATE` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `EXAM_TIPS_TOPIC` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `EXAM_TIPS_KEY` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `EXAM_TIPS_SOURCE` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `EXAM_TIPS_CHOICE` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `EXAM_TIPS_IMAGE` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `QUESTION_IMAGE` varchar(500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`QUESTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
